import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import {
	About,
	Featured,
	Footer,
	Gallery,
	Header,
	Navbar,
} from "../components/";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>The Mental States</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Header />
			<Featured />
			<About />
			<Gallery />
			<Footer />
		</div>
	);
}
